:  





In [182]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense

In [183]:
data = load_breast_cancer()

In [184]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [185]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [186]:
data['DESCR']

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance,

In [187]:
dscr = data['DESCR']

In [188]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [189]:

data['data'].shape

(569, 30)

In [190]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [191]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [192]:



j = 0
for i in data['feature_names']:
 print(i,":" ,data['data'][0][j])
 j+=1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [193]:
j = 0
for i in data['feature_names']:
 print(i,":" ,data['data'][2][j])
 j+=1

mean radius : 19.69
mean texture : 21.25
mean perimeter : 130.0
mean area : 1203.0
mean smoothness : 0.1096
mean compactness : 0.1599
mean concavity : 0.1974
mean concave points : 0.1279
mean symmetry : 0.2069
mean fractal dimension : 0.05999
radius error : 0.7456
texture error : 0.7869
perimeter error : 4.585
area error : 94.03
smoothness error : 0.00615
compactness error : 0.04006
concavity error : 0.03832
concave points error : 0.02058
symmetry error : 0.0225
fractal dimension error : 0.004571
worst radius : 23.57
worst texture : 25.53
worst perimeter : 152.5
worst area : 1709.0
worst smoothness : 0.1444
worst compactness : 0.4245
worst concavity : 0.4504
worst concave points : 0.243
worst symmetry : 0.3613
worst fractal dimension : 0.08758


In [194]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [195]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [196]:
data['data'].shape

(569, 30)

In [197]:

feature = data['data']

In [198]:

data['filename']

'/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv'

In [199]:

label = data['target']

In [200]:
label.shape

(569,)

In [201]:

feature.shape

(569, 30)

In [202]:
label.shape

(569,)

In [203]:

scale = StandardScaler()

feature = scale.fit_transform(feature)


In [204]:
j = 0
for i in data['feature_names']:
 print(i,":" ,feature[0][j])
 j+=1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [205]:


feature[0]

array([ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
        3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
        2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
        1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
        1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
        2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461])

In [206]:
label[0]

0

In [207]:
print(feature[100])
print(label[0])

[-0.1469182   1.32418299 -0.16142577 -0.20531322 -0.10534487 -0.3644556
 -0.03200659 -0.10392772 -0.73974915 -0.57946123  0.18525333  0.13271304
 -0.00250447  0.06166905 -0.38967544 -0.5923251  -0.17983429 -0.30416536
 -0.71343072 -0.54464557  0.1492672   1.56212414  0.0398769   0.0455596
 -0.25725505 -0.38146146  0.21450455  0.05776631 -0.40404995 -0.55281807]
0


In [208]:
data['target_names'][0]

'malignant'

In [209]:
print(feature[100])
print(data['target_names'][label[101]],label[101])

[-0.1469182   1.32418299 -0.16142577 -0.20531322 -0.10534487 -0.3644556
 -0.03200659 -0.10392772 -0.73974915 -0.57946123  0.18525333  0.13271304
 -0.00250447  0.06166905 -0.38967544 -0.5923251  -0.17983429 -0.30416536
 -0.71343072 -0.54464557  0.1492672   1.56212414  0.0398769   0.0455596
 -0.25725505 -0.38146146  0.21450455  0.05776631 -0.40404995 -0.55281807]
benign 1


In [210]:
[0]

[0]

In [211]:
df = pd.DataFrame(feature ,columns = data['feature_names'])

In [212]:
df

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0       1.097064     -2.073335  ...        2.750622                 1.937015
1       1.829821     -0.353632  ...       -0.243890                 0.281190
2       1.579888      0.456187  ...        1.152255                 0.201391
3      -0.768909      0.253732  ...        6.046041                 4.935010
4       1.750297     -1.151816  ...       -0.868353                -0.397100
..           ...           ...  ...             ...                      ...
564     2.110995      0.721473  ...       -1.360158                -0.709091
565     1.704854      2.085134  ...       -0.531855                -0.973978
566     0.702284      2.045574  ...       -1.104549                -0.318409
567     1.838341      2.336457  ...        1.919083                 2.219635
568    -1.808401      1.221792  ...       -0.048138                -0.751207

[569 rows x 30 columns]

In [213]:
#500 Training
x_train = feature[:500]
y_train = label[:500]

#35 Validation
x_val = feature[500:535]
y_val = label[500:535]


#34 Testing
x_test = feature[535:]
y_test = label[535:]


In [214]:
feature[:].shape

(569, 30)

In [215]:
label[:].shape

(569,)

In [216]:
feature[:500].shape

(500, 30)

In [217]:
x_train = feature[:500]
y_train = label[:500]

x_val = feature[500:535]
y_val = label[500:535]

x_test = feature[535:]
y_test = label[535:]



In [218]:
label[535:].shape

(34,)

In [219]:
feature[535:].shape

(34, 30)

In [220]:
x_train.shape

(500, 30)

In [221]:
x_test.shape

(34, 30)

In [222]:
y_val.shape

(35,)

In [223]:
y_train.shape

(500,)

In [224]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [225]:
y_train.shape

(500,)

In [226]:
x_val.shape

(35, 30)

In [227]:
x_test

array([[ 1.82414032,  0.36543133,  1.88778669, ...,  1.5256103 ,
         0.28512459, -0.45750286],
       [ 0.04053117,  0.75870568,  0.07418218, ...,  0.32879975,
        -0.32801426, -0.02415117],
       [-0.69222545,  1.19852137, -0.64252731, ...,  0.24657612,
        -0.1581473 ,  0.87303092],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [228]:

y_test

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [233]:
model = Sequential()


model.add(Dense(32, activation = 'relu', input_dim = 30))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

model.compile( loss = 'binary_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])


In [237]:
model.fit( x_train , y_train, epochs = 10, batch_size = 5, validation_data = (x_val, y_val))

Epoch 1/10
100/100 [==============================] - 1s 3ms/step - loss: 0.1961 - accuracy: 0.9160 - val_loss: 0.0337 - val_accuracy: 0.9714
Epoch 2/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0770 - accuracy: 0.9760 - val_loss: 0.0684 - val_accuracy: 0.9714
Epoch 3/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0572 - accuracy: 0.9820 - val_loss: 0.0859 - val_accuracy: 0.9429
Epoch 4/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0391 - accuracy: 0.9880 - val_loss: 0.1538 - val_accuracy: 0.9714
Epoch 5/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0395 - accuracy: 0.9840 - val_loss: 0.1185 - val_accuracy: 0.9714
Epoch 6/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0237 - accuracy: 0.9880 - val_loss: 0.0782 - val_accuracy: 0.9429
Epoch 7/10
100/100 [==============================] - 0s 2ms/step - loss: 0.0220 - accuracy: 0.9940 - val_loss: 0.0820 - val_accuracy: 0.9714
Epoch 

In [239]:
model.evaluate(x_test , y_test)

2/2 [==============================] - 0s 6ms/step - loss: 0.1220 - accuracy: 0.9706


[0.12203355133533478, 0.970588207244873]

In [240]:
model.evaluate(x_val , y_val)

2/2 [==============================] - 0s 9ms/step - loss: 0.1376 - accuracy: 0.9429


[0.13764074444770813, 0.9428571462631226]

In [241]:
for i in range(30):
  sample = x_test[i]
  sample = np.reshape(sample, (1,30))

  if (model.predict(sample)[0][0] > 0.5):
    print("-Benign")
  else:
    print("-Malignant")

  if (y_test[i] == 1):
    print("*Banign")
  else:
    print("*Melignant")
  print("-----------")

-Malignant
*Melignant
-----------
-Benign
*Melignant
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Benign
*Banign
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------
-Malignant
*Melignant
-----------


In [242]:
t = 0
for i in y_val:
  if (i == 1):
    t += 1

print(t)

26


In [ ]:
t = 0
for i in y_test:
  if (i == 1):
    t += 1

print(t)

18


In [244]:
x_test[0] * -.1

array([-0.18241403, -0.03654313, -0.18877867, -0.18575144, -0.05863832,
       -0.13182463, -0.15028386, -0.21481449, -0.11514395,  0.00407717,
       -0.10590431,  0.04114087, -0.0910827 , -0.10438254,  0.08210263,
       -0.00381089, -0.02704381, -0.03915519,  0.01286215,  0.04183096,
       -0.16630405,  0.00321166, -0.15768262, -0.16320758,  0.02441043,
       -0.03768171, -0.08209115, -0.15256103, -0.02851246,  0.04575029])

In [245]:
348/350

0.9942857142857143

In [246]:
347/350

0.9914285714285714

In [247]:
32/35

0.9142857142857143

In [248]:
model.predict(sample)

array([[1.3203235e-17]], dtype=float32)